
## Getting Ready

Before you can contribute to a package, you need to **get your system setup** for development.

1. If it's been a while, take the time to **update R and RStudio**.

1. **Install and configure git** (if you haven't already). https://github.mskcc.org/pages/datadojo/mskRutils/articles/git_config.html#git-setup

1. **Configure your GitHub Personal Access Token (PAT)**. Remember that Enterprise GitHub and public GitHub require two different PATs. Details here https://github.mskcc.org/pages/datadojo/mskRutils/articles/git_config.html#pat

1. **Install** the following packages

  ```r
  install.packages(c("devtools", "roxygen2", "testthat", "knitr", "styler"))
  ```

1. Using Windows? **Install RTools**. https://cran.r-project.org/bin/windows/Rtools/

1. Using macOS? **Install Xcode**.

  ```shell
  xcode-select --install
  ```
  
---
## Fork + Clone + Branch

.xlarge[
* Most R Package source code is kept on GitHub

* Navigate to the package's GitHub page
  - Fork the repository
  - Clone the forked repository from your personal GH page to your local machine
  - Create a _new_ branch to work on where you will add your function
  - Review the training materials for details on forking + cloning + branching [https://github.mskcc.org/datadojo/git_resources/tree/master/training/2022%2003%20Epi-Biostats%20Git%20Trainings](https://github.mskcc.org/datadojo/git_resources/tree/master/training/2022%2003%20Epi-Biostats%20Git%20Trainings)
]

---
## Install Package Dependencies

.xlarge[
- Each package has dependencies: packages that another package relies upon.
- Before you can contribute to a package, you must install that package _and_ all it's dependencies.
- There are different kinds of dependencies, and the most common are `Imports` (packages required to install the package) and `Suggests` (packages required to build the package, including packages used in documentation, vignettes, and unit testing).
- Before you can contribute to a package, you need to install _all_ of its dependencies.
- Open the package R project in RStudio, and run `renv::install()`; this will install all the dependencies.
]

---
## Write a Function
  
1. If you're adding a new function to a package, the code for the function will generally live in its own `.R` file by the same name. Run `usethis::use_r("foo")` and a blank script file will be added to the R folder. 
  
  ```r
  usethis::use_r("foo")
  #> √ Setting active project to 'C:/Users/SjobergD/GitHub/contributing-to-an-R-pkg'
  #> √ Creating 'R/'
  #> * Modify 'R/foo.R'
  #> * Call `use_test()` to create a matching test file
  ```
  
1. Write your function!

  ```r
  foo <- function(x) {
    # check input is numeric
    stopifnot(is.numeric(x))
    
    # return the mean
    mean(x)
  }
  ```
  
1. When writing function that utilize {tidyverse} functions, be sure to use the `.data` and `.env` prefixes. Review these slides for details [https://mskcc-epi-bio.github.io/Writing-Function-with-the-tidyverse/](https://mskcc-epi-bio.github.io/Writing-Function-with-the-tidyverse/)